
import datetime
import sys, os; sys.path.append(os.path.dirname(__file__))
from logger import logger

def simulate_llm_report(results):
    timestamp = datetime.datetime.now().isoformat()
    filename = f"scout_report_{timestamp}.md"
    path = f"./reports/{filename}"

    logger.info("Generating LLM-style report for Scout...")

    lines = [f"# AgentOS Health Report ({timestamp})", ""]
    for name, status, detail in results:
        lines.append(f"## {name.upper()}")
        lines.append(f"- Status: **{status.upper()}**")
        lines.append(f"- Detail: `{detail}`")
        lines.append("")

        if status != "ok":
            lines.append(f"> **Suggestion:** Please investigate `{name}` for issues. Consider adding retries or alerting.")
            lines.append("")

    lines.append("---")
    lines.append("_This report was generated by the Scout agent._")

    import os
    os.makedirs("./reports", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.success(f"Report saved to {path}")
    return path
